### ISSUE TITLE
Feedback - Didier from OpenBB

### ISSUE THREAD

**Issue by DidierRLopes** [GPTStonks/api#19]
Amazing project, very impressive.

I did a tweet about it - https://x.com/didier_lopes/status/1727146534754808042?s=20

A few people seem interested (including from our team), would love to chat 🙏🏽

If you add the tag "openbb" to this project, it will be automatically featured here: https://my.openbb.co/app/sdk/community-projects :)

**Comment by Dedalo314** [comment]
Hello Didier! Really glad that you find the project interesting! We would be more than happy to chat. If you want, feel free to write an email to gptstonks@gmail.com so we can set up a time.

Looking forward to hearing from you!
